all: task1 task2 task3 task4 task5 task6 task7 task8 task9 task10 task11

task1: 
	cd ../task1 && bash UniqueImages.sh
task2:
	cd ../task2 && bash archives.sh
task3:
	cd ../task3 && bash sshAuthenticationOnaServer.sh Nurt 192.168.0.103
task4:
	cd ../task4 && ./configApiLogs.sh web-service-gin

task5:
	cd ../task5 && bash systemdforAPI.sh
task6:
	cd ../task6 && bash 5top.sh
task7:
	cd ../task7 && bash RW-permissions-for-new-log-files.sh 
task8:
	cd ../task8 && bash new-job-name.sh task8name
task9:
	cd ../task9 && bash task9.sh 79.134.40.9 medhelper.xyz
task10:
	cd ../task10 && bash task10.sh
task11:
	cd ../task11 && bash init.sh 5